// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB35FUzDXGu-sEsmYKmjZCtEcLLOrHhO9c',
    appId: '1:771916086138:web:e8b42c143aa5585173b4c3',
    messagingSenderId: '771916086138',
    projectId: 'pizza-house-4319d',
    authDomain: 'pizza-house-4319d.firebaseapp.com',
    storageBucket: 'pizza-house-4319d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGf45vkYJgg0jXTJv9YFYCywvflaFltbE',
    appId: '1:771916086138:android:42688f579b2caaf773b4c3',
    messagingSenderId: '771916086138',
    projectId: 'pizza-house-4319d',
    storageBucket: 'pizza-house-4319d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAenf2wedAZlEUQa-QLM5PTU9jFL_qunqo',
    appId: '1:771916086138:ios:4ea46b16b4d7493973b4c3',
    messagingSenderId: '771916086138',
    projectId: 'pizza-house-4319d',
    storageBucket: 'pizza-house-4319d.appspot.com',
    iosBundleId: 'com.example.pizzaHouse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAenf2wedAZlEUQa-QLM5PTU9jFL_qunqo',
    appId: '1:771916086138:ios:4ea46b16b4d7493973b4c3',
    messagingSenderId: '771916086138',
    projectId: 'pizza-house-4319d',
    storageBucket: 'pizza-house-4319d.appspot.com',
    iosBundleId: 'com.example.pizzaHouse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB35FUzDXGu-sEsmYKmjZCtEcLLOrHhO9c',
    appId: '1:771916086138:web:e0ff39ee57cd904b73b4c3',
    messagingSenderId: '771916086138',
    projectId: 'pizza-house-4319d',
    authDomain: 'pizza-house-4319d.firebaseapp.com',
    storageBucket: 'pizza-house-4319d.appspot.com',
  );

}